### ISSUE TITLE
Error when unmounting component has componentWillMount() without componentWillUnmount() method defined 

### ISSUE THREAD

**Issue by ikido** [mweststrate/mobservable-react#9] opened 2015-12-02 13:55 UTC
Uncaught TypeError: Cannot read property 'forEach' of undefined

Error references to line 94 in `node_modules/mobservable-react/index.js`, that states

    this.__$mobDependencies.forEach(function(dep) {
        dep.setRefCount(-1);
    });

This happens when component has `@observer` decorator and has own `componentWillMount()` defined but does not have own `componentWillUnmount()`. Adding empty `componentWillUnmount()` method to component makes the error go away.

**Comment by mweststrate** [comment] 2015-12-02 14:30
Thanks for reporting! Will look into it. Quick upfront question: does this also happen if the `@autobind` isn't applied (if you used that here as well)?

**Comment by ikido** [comment] 2015-12-02 15:21
You were right, removing `@autobind` decorator also fixes the issue. I'm using https://github.com/andreypopp/autobind-decorator for that, would I have to bind methods manually to make `mobservable-react` work correctly?

**Comment by mweststrate** [comment] 2015-12-02 15:24
I can imagine a few things: swap the order of `@autobind`  and `@observer`. 

I don't autobind stuff, but for event handlers I just define initialized properties instead of functions so that you don't need binding:

e.g. instead of:

```javascript
onClick(event) {
    this.props.bla;
}
``` 

use:

```javascript
onClick = (event) => {
    this.props.bla;
}
```

**Comment by ikido** [comment] 2015-12-02 15:44
When using initialized properties I'm getting `forceUpdate` error mentioned in this issue: https://github.com/mweststrate/mobservable/issues/47

**Comment by mweststrate** [comment] 2015-12-02 15:58
Using jspm with hot reloading as well? Could you share a test setup somewhere?

**Comment by mweststrate** [comment] 2015-12-03 12:29
@ikido Were you able to make any progress on this issue? Is this also a problem without hot reloading?

**Comment by ikido** [comment] 2015-12-03 13:14
Not sure if it is problem with hot reloading — I'm using webpack + react-hot-loader, and I get `forceUpdate` bug when I need to unmount component and then mount it again. How should I debug this one? I think I'll have time during the weekend to play with it a bit more

**Comment by mweststrate** [comment] 2015-12-03 14:04
@ikido I think the easiest is to alter node_modules/mobservable-react/index.js with log statements in the different lifecycle methods, my best guess is that some of them aren't called during reloading, for example `componentWillMount` for the new instance, or `componentWillUnmount` for the old one.

**Comment by mweststrate** [comment] 2015-12-18 14:12
forceUpdate error might be a duplicate of: https://github.com/mweststrate/mobservable-react/issues/12

**Comment by mweststrate** [comment] 2015-12-18 18:23
Hi @ikido 

If this was still an issue, could you verify whether version 2.1.1 fixes it? 

Thanks!

**Comment by ikido** [comment] 2015-12-25 07:51
version 2.1.1 fixes forceUpdate error, you can close this issue — problem was in autobind decorator which I got rid of in favor initialized properties, as you suggested

**Closed** 2015-12-25 11:39 UTC
